# Generated by Django 3.2.2 on 2021-05-20 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_auto_20210518_1912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteer',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='post_img/'),
        ),
    ]
